/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Views;

import Models.Article;
import Models.Client;
import Models.Employe;
import Models.dataBase;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP PROBOOK 450 G1
 */
public class DetailVente extends javax.swing.JFrame {
    
    private Client Clt;
    private int idcmd;
    private Date datecmd;
    float tht=0;
    private Employe Emplo;
    
          
    
    /** Creates new form DetailVente */
    public DetailVente(Client Clt,int idcmd,Date d,Employe Emplo) {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ImageIcon icon = new ImageIcon(getClass().getResource("/Views/Logoo.png"));
        this.setIconImage(icon.getImage());
        this.Clt=Clt;
        this.idcmd=idcmd;
        this.datecmd=d;
        this.Emplo=Emplo;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Recu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbidclt = new javax.swing.JLabel();
        lbnom = new javax.swing.JLabel();
        lbprenom = new javax.swing.JLabel();
        lbcontact = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbcmd = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbdate = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDetailCmd = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtht = new javax.swing.JLabel();
        jtva = new javax.swing.JLabel();
        jttc = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnajouter = new javax.swing.JButton();
        cbxart = new javax.swing.JComboBox<>();
        txtart = new javax.swing.JFormattedTextField();
        btnEnregistrer = new javax.swing.JButton();
        btnSupp = new javax.swing.JButton();
        Imprimer = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204), 3));

        jLabel1.setText("Id Client:");

        jLabel2.setText("Nom:");

        jLabel3.setText("Prenom :");

        jLabel4.setText("Contact:");

        lbidclt.setText("jLabel6");

        lbnom.setText("jLabel7");

        lbprenom.setText("jLabel8");

        lbcontact.setText("jLabel9");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbidclt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbnom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbprenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbcontact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(274, 274, 274))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbidclt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbnom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbprenom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbcontact))
                .addContainerGap())
        );

        jLabel5.setText("Client:");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204), 3));

        jLabel7.setText("No de la commande :");

        lbcmd.setText("jLabel8");

        jLabel9.setText("Date de la commande :");

        lbdate.setText("jLabel10");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(116, 116, 116)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbdate, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(lbcmd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbcmd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbdate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setText("Commande :");

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204), 3));

        jDetailCmd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdVente", "IdProduit", "Nom du Produit", "Prix Unitaire", "Qté Vendu", "Sous Total"
            }
        ));
        jScrollPane1.setViewportView(jDetailCmd);

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        jLabel10.setText("Total HT");

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        jLabel11.setText("TVA (20%)");

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        jLabel12.setText("TTC");

        jtht.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jtht.setText("jLabel13");

        jtva.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jtva.setText("jLabel14");

        jttc.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jttc.setText("jLabel15");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(72, 72, 72)
                        .addComponent(jttc))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtva, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtht, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(44, 44, 44))
            .addComponent(jScrollPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtht))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jttc)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addContainerGap())))
        );

        jLabel8.setText("Détail de la commande :");

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204), 3));

        jLabel13.setText("Article");

        jLabel14.setText("Quantité");

        btnajouter.setText("Ajouter l'article");
        btnajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajouterActionPerformed(evt);
            }
        });

        cbxart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(76, 76, 76)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(cbxart, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtart, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(btnajouter)
                    .addComponent(cbxart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout RecuLayout = new javax.swing.GroupLayout(Recu);
        Recu.setLayout(RecuLayout);
        RecuLayout.setHorizontalGroup(
            RecuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecuLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(RecuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RecuLayout.createSequentialGroup()
                        .addGroup(RecuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RecuLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel8))
                            .addGroup(RecuLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel5)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RecuLayout.createSequentialGroup()
                        .addGroup(RecuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RecuLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(33, 33, 33))))
        );
        RecuLayout.setVerticalGroup(
            RecuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnEnregistrer.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnEnregistrer.setForeground(new java.awt.Color(0, 0, 255));
        btnEnregistrer.setText("Enregistrer les modifications");
        btnEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistrerActionPerformed(evt);
            }
        });

        btnSupp.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnSupp.setForeground(new java.awt.Color(255, 0, 51));
        btnSupp.setText("Supprimer l'aricle");
        btnSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuppActionPerformed(evt);
            }
        });

        Imprimer.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        Imprimer.setForeground(new java.awt.Color(255, 0, 255));
        Imprimer.setText("Imprimer");
        Imprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimerActionPerformed(evt);
            }
        });

        btnReturn.setText("Retour");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Recu, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnSupp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnregistrer)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(Imprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnReturn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btnReturn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Recu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSupp)
                    .addComponent(btnEnregistrer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Imprimer)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       
        try {
            lbidclt.setText(Clt.getIdclt()+"");
            lbnom.setText(Clt.getNom());
            lbprenom.setText(Clt.getPrenom());
            lbcontact.setText(Clt.getContact()+"");
            lbcmd.setText(idcmd+"");
            lbdate.setText(new SimpleDateFormat("dd/mm/yyyy").format(datecmd));
        
           Conn = (Connection) dataBase.getConnection();
            mystm  = Conn.prepareStatement("select IdVente,IdProduit,NomProduit,PrixUn,QteVendu,SousTotal from Vente join Produits using(IdProduit,NomProduit,PrixUn)  where nocmd=?");
            mystm.setInt(1,idcmd);
            rst = mystm.executeQuery();
            DefaultTableModel df = (DefaultTableModel) jDetailCmd.getModel();
            while(rst.next())
            {
                df.addRow(new Object[]{rst.getInt(1),rst.getString(2),rst.getString(3),rst.getInt(4),rst.getInt(5),rst.getFloat(6)});
                tht+=rst.getFloat(6);
            }
             rst=mystm.executeQuery("select* from Produits");
                while(rst.next()){
                   
                   cbxart.addItem(new Article(rst.getString(1),rst.getString(2),rst.getFloat(3),rst.getInt(4),rst.getString(5)));
               }
           
            
            
            jtht.setText(tht+"");
            jtva.setText((tht*0.2)+"");
            jttc.setText((tht*1.2)+"");
            
            
            
            rst.close();
            //Conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(DetailVente.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
    }//GEN-LAST:event_formWindowOpened

    private void btnajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajouterActionPerformed
        try{                                           
            // TODO add your handling code here:
            Article a = (Article) cbxart.getSelectedItem();
            String s =txtart.getText();
            int qte;
            
            try{
                qte = Integer.parseInt(s);
            }catch(NumberFormatException e){
                qte = 5;
            }
            DefaultTableModel df =(DefaultTableModel) jDetailCmd.getModel();
            df.addRow(new Object[]{" ",a.getId(),a.getNom(),a.getPrixUn(),qte,qte*a.getPrixUn()});
            tht+=a.getPrixUn()*qte;
            jtht.setText(tht+"");
            jtva.setText(tht*0.2+"");
            jttc.setText(tht*1.2+"");
            
            PreparedStatement ps =Conn.prepareStatement("update Commande set Total=? where nocmd=?");
            ps.setFloat(1, (float) (tht*1.2));
            ps.setInt(2, idcmd);
            ps.executeUpdate();
            
            PreparedStatement pslc =Conn.prepareStatement("insert into Vente values (IdVente,?,?,?,?,?,?) ");
            pslc.setString(1, a.getId());
            pslc.setString(2, a.getNom());
            pslc.setInt(3,qte);
            pslc.setFloat(4,a.getPrixUn());
            pslc.setInt(5, idcmd);
            pslc.setFloat(6, qte*a.getPrixUn());
            pslc.executeUpdate();
            
        }catch(SQLException ex){
            Logger.getLogger(DetailVente.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_btnajouterActionPerformed

    private void cbxartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxartActionPerformed

    private void btnSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuppActionPerformed
        try {
            // TODO add your handling code here:
            DefaultTableModel df=(DefaultTableModel) jDetailCmd.getModel();
            int l =jDetailCmd.getSelectedRow();
            int qt = 0;
            float pU = 0;
            if(l>-1)
            {   try {
                pU = (int) df.getValueAt(l, 3);
                qt=(int) df.getValueAt(l, 4);
                PreparedStatement pslc =Conn.prepareStatement("delete from Vente where IdVente=?  ");
                pslc.setInt(1, Integer.parseInt(df.getValueAt(l, 0).toString()));
                pslc.executeUpdate();
                
                df.removeRow(l);
            } catch (SQLException ex) {
                Logger.getLogger(DetailVente.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            tht-=qt*pU;
            jtht.setText(tht+"");
            jtva.setText(tht*0.2+"");
            jttc.setText(tht*1.2+"");
            PreparedStatement ps =Conn.prepareStatement("update Commande set Total=? where nocmd=?");
            ps.setFloat(1, (float) (tht*1.2));
            ps.setInt(2, idcmd);
            ps.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(DetailVente.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_btnSuppActionPerformed

    @SuppressWarnings("empty-statement")
    private void btnEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistrerActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Modifications éffectué avec succes.");
        DefaultTableModel df=(DefaultTableModel) jDetailCmd.getModel();
        
        int ltd=df.getRowCount();
        for(int l= ltd-1;l>=0;l--)
        {
            df.removeRow(l);
        }
     
     
        
    }//GEN-LAST:event_btnEnregistrerActionPerformed

    private void ImprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimerActionPerformed
        // TODO add your handling code here:
        new FrameRecu(Clt,idcmd, datecmd, Emplo).setVisible(true);
    }//GEN-LAST:event_ImprimerActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Imprimer;
    private javax.swing.JPanel Recu;
    private javax.swing.JButton btnEnregistrer;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSupp;
    private javax.swing.JButton btnajouter;
    private javax.swing.JComboBox<Article> cbxart;
    private javax.swing.JTable jDetailCmd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jtht;
    private javax.swing.JLabel jttc;
    private javax.swing.JLabel jtva;
    private javax.swing.JLabel lbcmd;
    private javax.swing.JLabel lbcontact;
    private javax.swing.JLabel lbdate;
    private javax.swing.JLabel lbidclt;
    private javax.swing.JLabel lbnom;
    private javax.swing.JLabel lbprenom;
    private javax.swing.JFormattedTextField txtart;
    // End of variables declaration//GEN-END:variables
    // Variables de connection
      private  Connection Conn = null;
      private PreparedStatement mystm = null; 
      private  ResultSet rst = null;
      
}
