/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Models.Employe;
import Models.dataBase;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author HP PROBOOK 450 G1
 */
public class FrameEmploye extends javax.swing.JFrame {
     private ArrayList<Employe> Emplo=new ArrayList<>();
    private int pos =0;
    /**
     * Creates new form FrameEmploye
     */
    public FrameEmploye() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ImageIcon icon = new ImageIcon(getClass().getResource("/Views/Logoo.png"));
        this.setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnmodifier = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnnouveau = new javax.swing.JButton();
        btnpreview = new javax.swing.JButton();
        txtlogin = new javax.swing.JTextField();
        btnprecedent = new javax.swing.JButton();
        BtnListCmd = new javax.swing.JButton();
        btnsuivant = new javax.swing.JButton();
        txtnom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtprenom = new javax.swing.JTextField();
        btnderriere = new javax.swing.JButton();
        txtrole = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnajouter = new javax.swing.JButton();
        txtpass = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnmodifier.setBackground(new java.awt.Color(153, 153, 153));
        btnmodifier.setText("Modifier");
        btnmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifierActionPerformed(evt);
            }
        });

        jLabel4.setText("Role de l'Employé");

        btnnouveau.setBackground(new java.awt.Color(153, 153, 153));
        btnnouveau.setText("Nouveau");
        btnnouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnouveauActionPerformed(evt);
            }
        });

        btnpreview.setBackground(new java.awt.Color(153, 153, 153));
        btnpreview.setText("|<");
        btnpreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpreviewActionPerformed(evt);
            }
        });

        btnprecedent.setBackground(new java.awt.Color(153, 153, 153));
        btnprecedent.setText("<<");
        btnprecedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprecedentActionPerformed(evt);
            }
        });

        BtnListCmd.setBackground(new java.awt.Color(153, 153, 153));
        BtnListCmd.setText("Liste des employés");
        BtnListCmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListCmdActionPerformed(evt);
            }
        });

        btnsuivant.setBackground(new java.awt.Color(153, 153, 153));
        btnsuivant.setText(">>");
        btnsuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuivantActionPerformed(evt);
            }
        });

        jLabel1.setText("Login");

        btnderriere.setBackground(new java.awt.Color(153, 153, 153));
        btnderriere.setText(">|");
        btnderriere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnderriereActionPerformed(evt);
            }
        });

        jLabel2.setText("Nom Employé");

        jLabel5.setText("Password de l'employé");

        btnajouter.setBackground(new java.awt.Color(153, 153, 153));
        btnajouter.setText("Ajouter");
        btnajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajouterActionPerformed(evt);
            }
        });

        jLabel3.setText("Prénom Employé");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtrole)
                            .addComponent(txtprenom)
                            .addComponent(txtnom, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txtlogin)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(86, Short.MAX_VALUE)
                                .addComponent(btnnouveau, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(btnpreview)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(47, 47, 47)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addComponent(btnprecedent)
                                                .addGap(55, 55, 55)
                                                .addComponent(btnsuivant))
                                            .addComponent(BtnListCmd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(27, 27, 27)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnderriere)
                                    .addComponent(btnmodifier, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtprenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtrole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpreview)
                    .addComponent(btnprecedent)
                    .addComponent(btnsuivant)
                    .addComponent(btnderriere))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnajouter)
                    .addComponent(btnmodifier)
                    .addComponent(btnnouveau))
                .addGap(18, 18, 18)
                .addComponent(BtnListCmd)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifierActionPerformed
        
         try {
             // TODO add your handling code here:

             Conn = (Connection) dataBase.getConnection();
             PreparedStatement mystm  = Conn.prepareStatement("update  Employees set NomEmploy=?,PrenomEmploy=?,Role=?"+"where Login=? or PassWord=?");
             
             String log=txtlogin.getText();
             String nom=txtnom.getText();
             String prenom=txtprenom.getText();
             String role=txtrole.getText();
             String passw=txtpass.getText();
             Employe c = new Employe(log, nom, prenom, role, passw);
             mystm.setString(4, log);
             mystm.setString(1, nom);
             mystm.setString(2, prenom);
             mystm.setString(3, role);
             mystm.setString(5, passw);
             mystm.executeUpdate();
             Emplo.add(c);
             c.setNom(nom);
             c.setPrenom(prenom);
             c.setRole(role);
             
             JOptionPane.showMessageDialog(null,"Informations de l'employé mis à jour avec succes.");
         } catch (SQLException ex) {
             Logger.getLogger(FrameEmploye.class.getName()).log(Level.SEVERE, null, ex);
         }
        

    }//GEN-LAST:event_btnmodifierActionPerformed

    private void btnnouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnouveauActionPerformed
       String a = null;
        
        txtlogin.setText(a);
        txtnom.setText("");
        txtprenom.setText("");
        txtrole.setText("");
        txtpass.setText("");
    }//GEN-LAST:event_btnnouveauActionPerformed

    private void btnpreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpreviewActionPerformed
        // TODO add your handling code here:
        try{
            pos=0;
            afficher();
        }catch(IndexOutOfBoundsException e)
        {
            JOptionPane.showMessageDialog(null, "Liste d'employe vide");
        }
    }//GEN-LAST:event_btnpreviewActionPerformed

    private void btnprecedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprecedentActionPerformed
        // TODO add your handling code here:
        try{
            pos--;
            afficher();
        }catch(IndexOutOfBoundsException e)
        {
            pos++;

        }
    }//GEN-LAST:event_btnprecedentActionPerformed

    private void BtnListCmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListCmdActionPerformed
        // TODO add your handling code here:
        new FrameListEmploy().setVisible(true);
    }//GEN-LAST:event_BtnListCmdActionPerformed

    private void btnsuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuivantActionPerformed
        // TODO add your handling code here:
        try{
            pos++;
            afficher();
        }catch(IndexOutOfBoundsException e)
        {
            pos--;
        }
    }//GEN-LAST:event_btnsuivantActionPerformed

    private void btnderriereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnderriereActionPerformed
        // TODO add your handling code here:
        try{
            pos=Emplo.size()-1;
            afficher();
        }catch(IndexOutOfBoundsException e)
        {
            JOptionPane.showMessageDialog(null, "Liste de clients vide");
        }
    }//GEN-LAST:event_btnderriereActionPerformed

    private void btnajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajouterActionPerformed
        try {
            // TODO add your handling code here:

            Conn = (Connection) dataBase.getConnection();
            PreparedStatement mystm  = Conn.prepareStatement("insert into Employees values(?,?,?,?,?)");
            String log=txtlogin.getText();
            String nom=txtnom.getText();
            String prenom=txtprenom.getText();
            String role=txtrole.getText();
            String passw=txtpass.getText();
            Employe c = new Employe(log, nom, prenom, role, passw);
            mystm.setString(1, log);
            mystm.setString(2, nom);
            mystm.setString(3, prenom);
            mystm.setString(4, role);
            mystm.setString(5, passw);
            mystm.executeUpdate();
            Emplo.add(c);
            JOptionPane.showMessageDialog(null,"Employé ajouté avec succès.");
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(FrameProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnajouterActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
           String sql1 ="select* from Employees"; 
        try {
             // TODO add your handling code here:
             
             Conn = (Connection) dataBase.getConnection();
             stm=Conn.createStatement();
             rst=stm.executeQuery(sql1);
             while(rst.next())
             {
                 Emplo.add(new Employe(rst.getString(1), rst.getString(2),rst.getString(3),rst.getString(4),rst.getString(5)));
             }
             rst.close();
             Conn.close();
             afficher();
         } catch (SQLException ex) {
             Logger.getLogger(FrameEmploye.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameEmploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameEmploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameEmploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameEmploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameEmploye().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnListCmd;
    private javax.swing.JButton btnajouter;
    private javax.swing.JButton btnderriere;
    private javax.swing.JButton btnmodifier;
    private javax.swing.JButton btnnouveau;
    private javax.swing.JButton btnprecedent;
    private javax.swing.JButton btnpreview;
    private javax.swing.JButton btnsuivant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtlogin;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtpass;
    private javax.swing.JTextField txtprenom;
    private javax.swing.JTextField txtrole;
    // End of variables declaration//GEN-END:variables
     private void afficher() {
         Employe Employ=Emplo.get(pos);
         txtlogin.setText(Employ.getLogin());
         txtnom.setText(Employ.getNom());
         txtprenom.setText(Employ.getPrenom());
         txtrole.setText(Employ.getRole());
         txtpass.setText(Employ.getPassword());
    }
  // Variables de connection
      private  Connection Conn = null;
      private  Statement stm = null;
      private  ResultSet rst = null;
      

}
