/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Models.Client;
import Models.Employe;
import Models.dataBase;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP PROBOOK 450 G1
 */
public class FrameRecherche extends javax.swing.JFrame {
        private Employe Emplo;
    /**
     * Creates new form FrameRecherche
     */
    public FrameRecherche() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/Logoo.png"));
        this.setIconImage(icon.getImage());
        this.setTitle("Burando Shoppu");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtdatedebut = new javax.swing.JTextField();
        txtdatefin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rdbnom = new javax.swing.JRadioButton();
        rdbdate = new javax.swing.JRadioButton();
        btnrechercher = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jresultrecherche = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnReturn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nom et Prénoms:");

        jLabel2.setText("Date Commande (yyyy/mm/dd)");

        jLabel3.setText("entre");

        jLabel4.setText("et");

        buttonGroup1.add(rdbnom);
        rdbnom.setSelected(true);

        buttonGroup1.add(rdbdate);

        btnrechercher.setText("Rechercher");
        btnrechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrechercherActionPerformed(evt);
            }
        });

        jresultrecherche.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Client", "Nom", "Prenoms", "Contact", "No Cmd", "Datecmd", "Total Cmd"
            }
        ));
        jScrollPane1.setViewportView(jresultrecherche);

        jButton1.setText("Détail de la commande");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnReturn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/L.png"))); // NOI18N
        btnReturn1.setBorderPainted(false);
        btnReturn1.setContentAreaFilled(false);
        btnReturn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbnom)
                            .addComponent(rdbdate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtdatedebut, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addComponent(txtdatefin, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(btnrechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnReturn1))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnReturn1)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbnom))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtdatedebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdatefin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(rdbdate))
                .addGap(18, 18, 18)
                .addComponent(btnrechercher)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnrechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrechercherActionPerformed
        try {
        // Connexion à la base de données
        Conn = (Connection) dataBase.getConnection();
        // Requête SQL de base avec une jointure
        String req = "SELECT IdClient, Nom, Prenom, Contact, nocmd, DateVente, Total "
                   + "FROM Clients "
                   + "JOIN Commande USING(IdClient) ";
                  /* + "JOIN Vente USING(nocmd) "
                   + "JOIN Produits  USING(IdProduit)";*/
                   
          String nom=txtnom.getText();
        // Ajout de la condition de recherche en fonction de la sélection de l'utilisateur
        if(rdbnom.isSelected()) {
            req += " WHERE (LOWER(Nom)=LOWER('"+nom+"') || LOWER(Prenom)=LOWER('"+nom+"'))";
        } else {
            req += " WHERE DateVente BETWEEN '"+txtdatedebut.getText()+"' AND '"+txtdatefin.getText()+"'";
        }
        
        // Ajout de la clause GROUP BY
        req += " GROUP BY IdClient, Nom, Prenom, Contact, nocmd, DateVente, Total";
        
        // Exécution de la requête
        stm=Conn.createStatement();
        rst = stm.executeQuery(req);
        
        // Nettoyage du modèle de tableau avant d'ajouter de nouvelles lignes
        DefaultTableModel df = (DefaultTableModel) jresultrecherche.getModel();
        df.setRowCount(0);
        
        // Ajout des résultats au modèle de tableau
        while(rst.next()) {
            df.addRow(new Object[]{rst.getInt(1), rst.getString(2), rst.getString(3), rst.getInt(4), rst.getInt(5), rst.getDate(6), rst.getFloat(7)});
        }
        
    } catch (SQLException ex) {
        Logger.getLogger(FrameRecherche.class.getName()).log(Level.SEVERE, null, ex);
    }

    }//GEN-LAST:event_btnrechercherActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            
            int row=jresultrecherche.getSelectedRow();
            DefaultTableModel df = (DefaultTableModel) jresultrecherche.getModel();
            
            int nocm=Integer.parseInt(df.getValueAt(row, 4).toString());
            java.util.Date datecmd=new SimpleDateFormat("yyyy-mm-dd").parse(df.getValueAt(row, 5).toString());
            int noclt=Integer.parseInt(df.getValueAt(row, 0).toString());
            String nom=(String) df.getValueAt(row,1);
            String prenom=(String) df.getValueAt(row,2);
            int tel=Integer.parseInt(df.getValueAt(row, 3).toString());
            
            
            new DetailVente(new Client(noclt,nom,prenom,tel),nocm ,datecmd,Emplo).setVisible(true);
        } catch (ParseException ex) {
            Logger.getLogger(FrameRecherche.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnReturn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturn1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnReturn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameRecherche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameRecherche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameRecherche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameRecherche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameRecherche().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturn1;
    private javax.swing.JButton btnrechercher;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jresultrecherche;
    private javax.swing.JRadioButton rdbdate;
    private javax.swing.JRadioButton rdbnom;
    private javax.swing.JTextField txtdatedebut;
    private javax.swing.JTextField txtdatefin;
    private javax.swing.JTextField txtnom;
    // End of variables declaration//GEN-END:variables
    // Variables de connection
      private  Connection Conn = null;
      private  Statement stm = null;
      private  ResultSet rst = null;
}
