package Views;


import Models.dataBase;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP PROBOOK 450 G1
 */
public class FrameListEmploy extends javax.swing.JFrame {

    DefaultTableModel tableau =new DefaultTableModel();
    /**
     * Creates new form Tableau
     */
    public FrameListEmploy() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/Logoo.png"));
        this.setIconImage(icon.getImage());
        this.setTitle("Burando Shoppu");
        tableau.addColumn("Matricule");
        tableau.addColumn("Nom");
        tableau.addColumn("Prenoms");
        tableau.addColumn("Role");
        tableau.addColumn("Password");
        
        
        Connection Conn = null;
        Statement stm = null;
        ResultSet rst = null;
       
     
        String sql1;
        sql1 = "select * from Employees";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("Pilote charge");
        }
        catch(ClassNotFoundException e){
            System.err.println(e.getMessage());
            System.exit(0);
        }
        
        try {
            Conn = (Connection) dataBase.getConnection();
            System.out.println("Pilote charge, connexion ouverte");
             
            try{
                stm =Conn.createStatement();
                rst= stm.executeQuery(sql1);
                while (rst.next()){
                   
                    tableau.addRow(new Object[]{rst.getString("Login"),rst.getString("NomEmploy"),rst.getString("PrenomEmploy"),rst.getString("Role"),rst.getString("PassWord")});
                   
                }
            }
            catch(SQLException sql){
                System.out.println(sql.getMessage());
                System.exit(0);
            }
             finally{
                stm.close();
            }      
                    
        }
        catch(SQLException seq){
            System.out.println(seq.getMessage());
            System.exit(0);
        }
        finally{
            try {if (Conn != null) Conn.close();
                System.out.print("Connexion fermée");
               }
               catch(SQLException se){
                
                }  
               jTable1.setModel(tableau);
            }
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
