/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Models.Article;
import Models.Client;
import Models.Employe;
import Models.dataBase;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP PROBOOK 450 G1
 */
public class FrameNewCmd extends javax.swing.JFrame {
 float tht;
  int qte;  
  Client clt;
   private Date datecmd;
    private Employe Emplo;
    int nocmd;

    /**
     * Creates new form FrameNewCmd
     */
    public FrameNewCmd(Employe Emplo) {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ImageIcon icon = new ImageIcon(getClass().getResource("/Views/Logoo.png"));
        this.setIconImage(icon.getImage());
        this.Emplo=Emplo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxClt = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        lbidclt = new javax.swing.JLabel();
        lbnom = new javax.swing.JLabel();
        lbprenom = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbcontact = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnajouter = new javax.swing.JButton();
        cbxart = new javax.swing.JComboBox<>();
        txtart = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jArt = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbtva = new javax.swing.JFormattedTextField();
        lbtht = new javax.swing.JFormattedTextField();
        lbttc = new javax.swing.JFormattedTextField();
        btnEnregistrer = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnImprimer = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 3));

        jLabel1.setText("Choisir Client");

        jLabel2.setText("Id Client");

        jLabel3.setText("Nom");

        cbxClt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCltItemStateChanged(evt);
            }
        });
        cbxClt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCltActionPerformed(evt);
            }
        });

        jLabel4.setText("Prenom");

        lbidclt.setText("jLabel5");

        lbnom.setText("jLabel6");

        lbprenom.setText("jLabel7");

        jLabel8.setText("Contact");

        lbcontact.setText("jLabel9");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxClt, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbidclt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                        .addComponent(lbnom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbprenom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbcontact, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cbxClt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbidclt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbnom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbprenom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbcontact)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 3));

        jLabel5.setText("Article");

        jLabel6.setText("Quantité");

        btnajouter.setText("Ajouter l'article");
        btnajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajouterActionPerformed(evt);
            }
        });

        cbxart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(76, 76, 76)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbxart, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btnajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtart, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnajouter)
                    .addComponent(cbxart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 3));

        jArt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Produit", "Nom du Produit", "Qté Vendu", "Prix Unitaire", "Sous Total"
            }
        ));
        jScrollPane1.setViewportView(jArt);

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("THT :");

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("TVA(20%) :");

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("TTC :");

        lbtva.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        lbtva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbtvaActionPerformed(evt);
            }
        });

        lbtht.setText("\n");
        lbtht.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N

        lbttc.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        lbttc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbttcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(123, 123, 123)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbtht, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(lbtva, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbttc))
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbtht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(lbtva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lbttc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnEnregistrer.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnEnregistrer.setForeground(new java.awt.Color(51, 102, 255));
        btnEnregistrer.setText("Enregistrer la commande\n");
        btnEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistrerActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Supprimer l'article");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEnregistrer)
                    .addComponent(jButton1))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btnImprimer.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnImprimer.setForeground(new java.awt.Color(255, 0, 255));
        btnImprimer.setText("Imprimer");
        btnImprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(btnImprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImprimer)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            // TODO add your handling code here:
            Conn = (Connection) dataBase.getConnection();
            stm = Conn.createStatement();
            rst = stm.executeQuery("select* from Clients");
            while(rst.next())
            {
                cbxClt.addItem(new Client(rst.getInt(1),rst.getString(2),rst.getString(3),rst.getInt(4)));
           
            }
            rst.close();
            rst=stm.executeQuery("select* from Produits");
                while(rst.next()){
                   
                   cbxart.addItem(new Article(rst.getString(1),rst.getString(2),rst.getFloat(3),rst.getInt(4),rst.getString(5)));
               }
            rst.close();
        } catch (SQLException ex) {
            Logger.getLogger(FrameNewCmd.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void cbxCltItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCltItemStateChanged
        // TODO add your handling code here:
        clt=(Client) cbxClt.getSelectedItem();
        lbidclt.setText(clt.getIdclt()+"");
        lbnom.setText(clt.getNom());
        lbprenom.setText(clt.getPrenom());
        lbcontact.setText(clt.getContact()+"");
        
    }//GEN-LAST:event_cbxCltItemStateChanged

    private void btnajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajouterActionPerformed
        // TODO add your handling code here:
        Article a = (Article) cbxart.getSelectedItem();
        String s =txtart.getText();
        
        try{
            qte = Integer.parseInt(s);
        }catch(NumberFormatException e){
            qte = 5;
        }
        DefaultTableModel df =(DefaultTableModel) jArt.getModel();
        df.addRow(new Object[]{a.getId(),a.getNom(),qte,a.getPrixUn(),qte*a.getPrixUn()});
        tht+=a.getPrixUn()*qte;
        lbtht.setText(tht+"");
        lbtva.setText(tht*0.2+"");
        lbttc.setText(tht*1.2+"");
    }//GEN-LAST:event_btnajouterActionPerformed
    
    private void cbxCltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCltActionPerformed

    private void cbxartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxartActionPerformed

    private void btnEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistrerActionPerformed
        String sql1="insert into Commande values(?,?,?,?)";
        String sql2 = "select* from Commande";
        String sql3="select* from Produits where IdProduit=?";
        
        try {
         // TODO add your handling code here:
         Conn = (Connection) dataBase.getConnection();
         PreparedStatement ps;
         
         stm=Conn.createStatement();
         rst=stm.executeQuery(sql2);
            nocmd = 1;
            while(rst.next())
            {
               nocmd=rst.getInt(1)+1;
               
            }
         rst.close();
         ps = Conn.prepareStatement(sql1,Statement.RETURN_GENERATED_KEYS);
         Date lcd=new Date();
         datecmd= new java.sql.Date(lcd.getTime());
         ps.setInt(1, nocmd);
         ps.setDate(2, (java.sql.Date) datecmd);
         ps.setString(3,lbttc.getText());
         ps.setString(4,lbidclt.getText());
        
         ps.executeUpdate();
         rst=ps.getGeneratedKeys();
         DefaultTableModel df=(DefaultTableModel) jArt.getModel();
         int cnt=jArt.getRowCount();
         PreparedStatement pslc =Conn.prepareStatement("insert into Vente values (IdVente,?,?,?,?,?,?) ");
         pslc.setInt(5, nocmd);
         for(int i=0;i<cnt;i++)
         {
            pslc.setString(1, df.getValueAt(i, 0).toString());
            pslc.setString(2, df.getValueAt(i,1).toString());
            pslc.setString(3,df.getValueAt(i,2).toString());
            pslc.setString(4,df.getValueAt(i,3).toString());
            pslc.setString(6,df.getValueAt(i,4).toString());
            //Récupération du stock disponible
            PreparedStatement pslcc=Conn.prepareStatement(sql3);
            pslcc.setString(1, df.getValueAt(i, 0).toString());
            ResultSet rs=pslcc.executeQuery();
            int stck=0;
            while(rs.next())
            {
                stck = rs.getInt(4);  
            }
           
            //Mise à jour du stock Disponible
            PreparedStatement psl =Conn.prepareStatement("update Produits set StockDispo=? where Idproduit=?");
            int reste=stck-qte;
            psl.setInt(1, reste);
            psl.setString(2, df.getValueAt(i, 0).toString());
            psl.executeUpdate();
            
            
            pslc.executeUpdate();
            
         
         }
         JOptionPane.showMessageDialog(null,"Commande sauvegarde avec succes");
        int response = JOptionPane.showConfirmDialog(null, "Voulez-vous enrégistrez le reçu ?", "Impression du reçu", JOptionPane.YES_NO_OPTION);
         if(response==JOptionPane.YES_OPTION)
         {
             new FrameRecu(clt,nocmd, datecmd, Emplo).setVisible(true);
             df.setRowCount(0);
             tht=0;
             lbtht.setText("0.0");
             lbtva.setText("0.0");
             lbttc.setText("0.0");
         }
        df.setRowCount(0);
         tht=0;
         lbtht.setText("0.0");
         lbtva.setText("0.0");
         lbttc.setText("0.0");
     } catch (SQLException ex) {
         Logger.getLogger(FrameNewCmd.class.getName()).log(Level.SEVERE, null, ex);
     }
            
    }//GEN-LAST:event_btnEnregistrerActionPerformed
public void imprimerRecu(){
    
}
    private void lbtvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbtvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbtvaActionPerformed

    private void lbttcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbttcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbttcActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel df=(DefaultTableModel) jArt.getModel();
        int l =jArt.getSelectedRow();
        int qt = 0;
        float pU = 0;
        if(l>-1)
        {
            qt= (int) df.getValueAt(l, 2);
            pU= (float) df.getValueAt(l, 3);
            df.removeRow(l);
        }
        tht-=qt*pU;
        lbtht.setText(tht+"");
        lbtva.setText(tht*0.2+"");
        lbttc.setText(tht*1.2+"");
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnImprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimerActionPerformed
        // TODO add your handling code here:
        new FrameRecu(clt,nocmd, datecmd, Emplo).setVisible(true);
    }//GEN-LAST:event_btnImprimerActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnregistrer;
    private javax.swing.JButton btnImprimer;
    private javax.swing.JButton btnajouter;
    private javax.swing.JComboBox<Client> cbxClt;
    private javax.swing.JComboBox<Article> cbxart;
    private javax.swing.JTable jArt;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbcontact;
    private javax.swing.JLabel lbidclt;
    private javax.swing.JLabel lbnom;
    private javax.swing.JLabel lbprenom;
    private javax.swing.JFormattedTextField lbtht;
    private javax.swing.JFormattedTextField lbttc;
    private javax.swing.JFormattedTextField lbtva;
    private javax.swing.JFormattedTextField txtart;
    // End of variables declaration//GEN-END:variables
   // Variables de connection
      private  Connection Conn = null;
      private  Statement stm = null;
      private  ResultSet rst = null;

}
