/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Models.Article;
import Models.dataBase;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author HP PROBOOK 450 G1
 */
public class FrameProduit extends javax.swing.JFrame {
     private ArrayList<Article> Clts=new ArrayList<Article>();
    private int pos =0;
    
    /**
     * Creates new form FrameProduit
     */
    public FrameProduit() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ImageIcon icon = new ImageIcon(getClass().getResource("/Views/Logoo.png"));
        this.setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnpreview = new javax.swing.JButton();
        btnprecedent = new javax.swing.JButton();
        btnsuivant = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnderriere = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnajouter = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnmodifier = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnnouveau = new javax.swing.JButton();
        txtidart = new javax.swing.JTextField();
        BtnListCmd = new javax.swing.JButton();
        txtnom = new javax.swing.JTextField();
        txtprix = new javax.swing.JTextField();
        txtqte = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcard = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnpreview.setBackground(new java.awt.Color(153, 153, 153));
        btnpreview.setText("|<");
        btnpreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpreviewActionPerformed(evt);
            }
        });

        btnprecedent.setBackground(new java.awt.Color(153, 153, 153));
        btnprecedent.setText("<<");
        btnprecedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprecedentActionPerformed(evt);
            }
        });

        btnsuivant.setBackground(new java.awt.Color(153, 153, 153));
        btnsuivant.setText(">>");
        btnsuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuivantActionPerformed(evt);
            }
        });

        jLabel1.setText("Id Produit");

        btnderriere.setBackground(new java.awt.Color(153, 153, 153));
        btnderriere.setText(">|");
        btnderriere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnderriereActionPerformed(evt);
            }
        });

        jLabel2.setText("Nom Produit");

        btnajouter.setBackground(new java.awt.Color(153, 153, 153));
        btnajouter.setText("Ajouter");
        btnajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajouterActionPerformed(evt);
            }
        });

        jLabel3.setText("Prix Un Produit");

        btnmodifier.setBackground(new java.awt.Color(153, 153, 153));
        btnmodifier.setText("Modifier");
        btnmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifierActionPerformed(evt);
            }
        });

        jLabel4.setText("Qté  du  Produit");

        btnnouveau.setBackground(new java.awt.Color(153, 153, 153));
        btnnouveau.setText("Nouveau");
        btnnouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnouveauActionPerformed(evt);
            }
        });

        BtnListCmd.setBackground(new java.awt.Color(153, 153, 153));
        BtnListCmd.setText("Liste des produits");
        BtnListCmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListCmdActionPerformed(evt);
            }
        });

        jLabel5.setText("Id Catégorie");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtqte)
                            .addComponent(txtprix)
                            .addComponent(txtnom, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txtidart)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE)
                                .addComponent(btnnouveau, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(btnpreview))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addComponent(btnprecedent)
                                                .addGap(55, 55, 55)
                                                .addComponent(btnsuivant))
                                            .addComponent(BtnListCmd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(27, 27, 27)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnderriere)
                                    .addComponent(btnmodifier, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(txtcard, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtidart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtprix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtqte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtcard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpreview)
                    .addComponent(btnprecedent)
                    .addComponent(btnsuivant)
                    .addComponent(btnderriere))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnajouter)
                    .addComponent(btnmodifier)
                    .addComponent(btnnouveau))
                .addGap(18, 18, 18)
                .addComponent(BtnListCmd)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpreviewActionPerformed
        // TODO add your handling code here:
        try{
            pos=0;
            afficher();
        }catch(IndexOutOfBoundsException e)
        {
            JOptionPane.showMessageDialog(null, "Liste de produit vide");
        }
    }//GEN-LAST:event_btnpreviewActionPerformed

    private void btnprecedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprecedentActionPerformed
        // TODO add your handling code here:
        try{
            pos--;
            afficher();
        }catch(IndexOutOfBoundsException e)
        {
            pos++;

        }
    }//GEN-LAST:event_btnprecedentActionPerformed

    private void btnsuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuivantActionPerformed
        // TODO add your handling code here:
        try{
            pos++;
            afficher();
        }catch(IndexOutOfBoundsException e)
        {
            pos--;
        }
    }//GEN-LAST:event_btnsuivantActionPerformed

    private void btnderriereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnderriereActionPerformed
        // TODO add your handling code here:
        try{
            pos=Clts.size()-1;
            afficher();
        }catch(IndexOutOfBoundsException e)
        {
            JOptionPane.showMessageDialog(null, "Liste de produits vide");
        }
    }//GEN-LAST:event_btnderriereActionPerformed

    private void btnajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajouterActionPerformed
         try {
             // TODO add your handling code here:
             
             
             Conn = (Connection) dataBase.getConnection();
             PreparedStatement mystm  = Conn.prepareStatement("insert into Produits values(?,?,?,?,?)");
             String id=txtidart.getText();
             String nom=txtnom.getText();
             int prix=Integer.parseInt(txtprix.getText());
             int qte=Integer.parseInt(txtqte.getText());
             String idcart=txtidart.getText();
             Article c = new Article(id, nom, prix, qte, idcart);
             mystm.setString(1, id);
             mystm.setString(2, nom);
             mystm.setFloat(3, prix);
             mystm.setInt(4, qte);
             mystm.setString(5, idcart);
             mystm.executeUpdate();
             Clts.add(c);
             JOptionPane.showMessageDialog(null,"Produit ajouté avec succès.");
         } catch (SQLException ex) {
             java.util.logging.Logger.getLogger(FrameProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         }

      

    }//GEN-LAST:event_btnajouterActionPerformed

    private void btnmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifierActionPerformed
         try {
             // TODO add your handling code here:
             
             
             Conn = (Connection) dataBase.getConnection();
             PreparedStatement mystm  = Conn.prepareStatement("update  Produits set NomProduit=?,PrixUn=?,StockDispo=? where IdProduit=? or IdCategorie=?");
             
             String id=txtidart.getText();
             String nom=txtnom.getText();
             Float prix=Float.parseFloat(txtprix.getText());
             int qte=Integer.parseInt(txtqte.getText());
             String idcart=txtcard.getText();
             Article c = new Article(id, nom, prix, qte, idcart);
             mystm.setString(1, nom);
             mystm.setFloat(2, prix);
             mystm.setInt(3, qte);
             mystm.setString(4, id);
             mystm.setString(5, idcart);
             mystm.executeUpdate();
             Clts.add(c);
             c.setNom(nom);
             c.setPrixUn(prix);
             c.setQte_stock(qte);
             
             JOptionPane.showMessageDialog(null,"Produit modifié avec succès.");
         } catch (SQLException ex) {
             java.util.logging.Logger.getLogger(FrameProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
         }

        

    }//GEN-LAST:event_btnmodifierActionPerformed

    private void btnnouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnouveauActionPerformed
         String a = null;
            txtidart.setText(a);
            txtnom.setText("");
            txtprix.setText("");
            txtqte.setText("");
            txtcard.setText("");

    }//GEN-LAST:event_btnnouveauActionPerformed

    private void BtnListCmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListCmdActionPerformed
        // TODO add your handling code here:
        new FrameListeProduit().setVisible(true);
    }//GEN-LAST:event_BtnListCmdActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String sql1 ="select* from Produits"; 
        try {
             // TODO add your handling code here:
             Conn = (Connection) dataBase.getConnection();
             stm=Conn.createStatement();
             rst=stm.executeQuery(sql1);
             while(rst.next())
             {
                 Clts.add(new Article(rst.getString(1), rst.getString(2),rst.getInt(3),rst.getInt(4),rst.getString(5)));
             }
             rst.close();
             Conn.close();
             afficher();
         } catch (SQLException ex) {
             Logger.getLogger(FrameProduit.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameProduit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameProduit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnListCmd;
    private javax.swing.JButton btnajouter;
    private javax.swing.JButton btnderriere;
    private javax.swing.JButton btnmodifier;
    private javax.swing.JButton btnnouveau;
    private javax.swing.JButton btnprecedent;
    private javax.swing.JButton btnpreview;
    private javax.swing.JButton btnsuivant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtcard;
    private javax.swing.JTextField txtidart;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprix;
    private javax.swing.JTextField txtqte;
    // End of variables declaration//GEN-END:variables
 private void afficher() {
         Article Art=Clts.get(pos);
         txtidart.setText(Art.getId());
         txtnom.setText(Art.getNom());
         txtprix.setText(Art.getPrixUn()+"");
         txtqte.setText(Art.getQte_stock()+"");
         txtcard.setText(Art.getIdcart());
    }
  // Variables de connection
      private  Connection Conn = null;
      private  Statement stm = null;
      private  ResultSet rst = null;
      
      
}
