/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Models.Client;
import Models.Employe;
import Models.dataBase;
import java.sql.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author HP PROBOOK 450 G1
 */
public class FrameClient extends javax.swing.JFrame {

    
    private ArrayList<Client> Clts=new ArrayList<Client>();
    private int pos =0;
    Employe Emplo;
    /**
     * Creates new form FrameClient
     */
    public FrameClient(Employe Emplo) {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.Emplo=Emplo;
    ImageIcon icon = new ImageIcon(getClass().getResource("/img/Logoo.png"));
        this.setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReturn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtidclt = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtprenom = new javax.swing.JTextField();
        txtcontact = new javax.swing.JTextField();
        btnpreview = new javax.swing.JButton();
        btnprecedent = new javax.swing.JButton();
        btnsuivant = new javax.swing.JButton();
        btnderriere = new javax.swing.JButton();
        btnajouter = new javax.swing.JButton();
        btnmodifier = new javax.swing.JButton();
        btnnouveau = new javax.swing.JButton();
        BtnListCmd = new javax.swing.JButton();
        btnReturn1 = new javax.swing.JButton();

        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/L.png"))); // NOI18N
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        jLabel1.setText("Id CLient");

        jLabel2.setText("Nom CLient");

        jLabel3.setText("Prenom CLient");

        jLabel4.setText("Contact du Client");

        btnpreview.setBackground(new java.awt.Color(153, 153, 153));
        btnpreview.setText("|<");
        btnpreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpreviewActionPerformed(evt);
            }
        });

        btnprecedent.setBackground(new java.awt.Color(153, 153, 153));
        btnprecedent.setText("<<");
        btnprecedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprecedentActionPerformed(evt);
            }
        });

        btnsuivant.setBackground(new java.awt.Color(153, 153, 153));
        btnsuivant.setText(">>");
        btnsuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuivantActionPerformed(evt);
            }
        });

        btnderriere.setBackground(new java.awt.Color(153, 153, 153));
        btnderriere.setText(">|");
        btnderriere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnderriereActionPerformed(evt);
            }
        });

        btnajouter.setBackground(new java.awt.Color(153, 153, 153));
        btnajouter.setText("Ajouter");
        btnajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajouterActionPerformed(evt);
            }
        });

        btnmodifier.setBackground(new java.awt.Color(153, 153, 153));
        btnmodifier.setText("Modifier");
        btnmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifierActionPerformed(evt);
            }
        });

        btnnouveau.setBackground(new java.awt.Color(153, 153, 153));
        btnnouveau.setText("Nouveau");
        btnnouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnouveauActionPerformed(evt);
            }
        });

        BtnListCmd.setBackground(new java.awt.Color(153, 153, 153));
        BtnListCmd.setText("Liste des commandes");
        BtnListCmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListCmdActionPerformed(evt);
            }
        });

        btnReturn1.setBackground(new java.awt.Color(102, 255, 255));
        btnReturn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/L.png"))); // NOI18N
        btnReturn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcontact)
                            .addComponent(txtprenom)
                            .addComponent(txtnom, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txtidclt)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(btnpreview)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(15, Short.MAX_VALUE)
                                .addComponent(btnnouveau, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(btnprecedent)
                                        .addGap(55, 55, 55)
                                        .addComponent(btnsuivant))
                                    .addComponent(BtnListCmd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnderriere)
                            .addComponent(btnmodifier, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnReturn1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnReturn1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtidclt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtprenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtcontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpreview)
                    .addComponent(btnprecedent)
                    .addComponent(btnsuivant)
                    .addComponent(btnderriere))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnajouter)
                    .addComponent(btnmodifier)
                    .addComponent(btnnouveau))
                .addGap(18, 18, 18)
                .addComponent(BtnListCmd)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         String sql1 ="select* from Clients";
        try {
            
            Conn = (Connection) dataBase.getConnection();
            stm=Conn.createStatement();
            rst=stm.executeQuery(sql1);
            while(rst.next())
            {
                Clts.add(new Client(rst.getInt(1), rst.getString(2),rst.getString(3),rst.getInt(4)));
            }
            rst.close();
            Conn.close();
            afficher();
        } catch (SQLException ex) {
            Logger.getLogger(FrameClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnpreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpreviewActionPerformed
        // TODO add your handling code here:
         try{
            pos=0;
            afficher();
        }catch(IndexOutOfBoundsException e)
        {
            JOptionPane.showMessageDialog(null, "Liste de clients vide");
        }
    }//GEN-LAST:event_btnpreviewActionPerformed

    private void btnprecedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprecedentActionPerformed
        // TODO add your handling code here:
        try{
            pos--;
            afficher();
        }catch(IndexOutOfBoundsException e)
        {
            pos++;
            
        }
    }//GEN-LAST:event_btnprecedentActionPerformed

    private void btnsuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuivantActionPerformed
        // TODO add your handling code here:
        try{
            pos++;
            afficher();
        }catch(IndexOutOfBoundsException e)
        {
          pos--;
        }
    }//GEN-LAST:event_btnsuivantActionPerformed

    private void btnderriereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnderriereActionPerformed
        // TODO add your handling code here:
        try{
            pos=Clts.size()-1;
            afficher();
        }catch(IndexOutOfBoundsException e)
        {
            JOptionPane.showMessageDialog(null, "Liste de clients vide");
        }
    }//GEN-LAST:event_btnderriereActionPerformed

    private void btnnouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnouveauActionPerformed
        // TODO add your handling code here:
         String sql1 ="select* from Clients";
         int i=0;
        try {
            Conn = (Connection) dataBase.getConnection();
            stm=Conn.createStatement();
            rst=stm.executeQuery(sql1);
            i=1;
            while(rst.next())
            {
               i=rst.getInt(1)+1;
               
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(FrameClient.class.getName()).log(Level.SEVERE, null, ex);
        }
           String a=""+i;
           
        txtidclt.setText(a);
        txtnom.setText("");
        txtprenom.setText("");
        txtcontact.setText("");
        
    }//GEN-LAST:event_btnnouveauActionPerformed

    private void btnajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajouterActionPerformed
        // TODO add your handling code here:
        
       try {
            Conn = (Connection) dataBase.getConnection();
            PreparedStatement mystm  = Conn.prepareStatement("insert into Clients values(?,?,?,?)");
            int idclt=Integer.parseInt(txtidclt.getText());
            String nom=txtnom.getText();
            String prenom=txtprenom.getText();
            int contact=Integer.parseInt(txtcontact.getText());
            
            Client c = new Client(idclt,nom,prenom,contact);
            mystm.setInt(1, idclt);
            mystm.setString(2, nom);
            mystm.setString(3, prenom);
            mystm.setInt(4, contact);
            mystm.executeUpdate();
            Clts.add(c);
            JOptionPane.showMessageDialog(null,"Client ajouté avec succès.");
            
        } catch (SQLException ex) {
            Logger.getLogger(FrameClient.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }//GEN-LAST:event_btnajouterActionPerformed

    private void btnmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifierActionPerformed
        // TODO add your handling code here:
              
        try {
            Conn = (Connection) dataBase.getConnection();
            PreparedStatement mystm  = Conn.prepareStatement("update  Clients set Nom=?,Prenom=?,Contact=?"+"where IdClient=?");
            
            String nom=txtnom.getText();
            String prenom=txtprenom.getText();
            int contact=Integer.parseInt(txtcontact.getText());
            
            Client c = Clts.get(pos);
            mystm.setInt(1, c.getIdclt());
            mystm.setString(2, nom);
            mystm.setString(3, prenom);
            mystm.setInt(4, contact);
            mystm.executeUpdate();
            c.setNom(nom);
            c.setPrenom(prenom);
            c.setContact(contact);
            
            JOptionPane.showMessageDialog(null,"Client modifié avec succès.");
            
        } catch (SQLException ex) {
            Logger.getLogger(FrameClient.class.getName()).log(Level.SEVERE, null, ex);
        }
           
           
    }//GEN-LAST:event_btnmodifierActionPerformed

    private void BtnListCmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListCmdActionPerformed
        // TODO add your handling code here:
        new FrameListCmd(Clts.get(pos),Emplo).setVisible(true);
    }//GEN-LAST:event_BtnListCmdActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        new FrameClient(Emplo).setVisible(true);
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnReturn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturn1ActionPerformed
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_btnReturn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnListCmd;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnReturn1;
    private javax.swing.JButton btnajouter;
    private javax.swing.JButton btnderriere;
    private javax.swing.JButton btnmodifier;
    private javax.swing.JButton btnnouveau;
    private javax.swing.JButton btnprecedent;
    private javax.swing.JButton btnpreview;
    private javax.swing.JButton btnsuivant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtidclt;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprenom;
    // End of variables declaration//GEN-END:variables
   // Variables de connection
      private  Connection Conn = null;
      private  Statement stm = null;
      private  ResultSet rst = null;
      
      
    private void afficher() {
         Client Clt=Clts.get(pos);
         txtidclt.setText(Clt.getIdclt()+"");
         txtnom.setText(Clt.getNom());
         txtprenom.setText(Clt.getPrenom());
         txtcontact.setText(Clt.getContact()+"");
    }
}